### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by supmyhava** [Fairmont77/OKX_Racer_bot#2]
hi mate i try use your bot 
i had 67000 points in my account and when i run your bot it put me balancePoints: 17967
my points are gone ????

**Comment by Fairmont77** [comment]
> hi mate i try use your bot 
> 
> i had 67000 points in my account and when i run your bot it put me balancePoints: 17967
> 
> my points are gone ????

Hi, I don't think so! He must have upgraded up your boosts

**Comment by supmyhava** [comment]
> > hi mate i try use your bot
> > i had 67000 points in my account and when i run your bot it put me balancePoints: 17967
> > my points are gone ????
> 
> Hi, I don't think so! He must have upgraded up your boosts

ah you mean that he used the points up upgrade ? how much that costs ?

**Comment by Fairmont77** [comment]
> > > hi mate i try use your bot
> > > i had 67000 points in my account and when i run your bot it put me balancePoints: 17967
> > > my points are gone ????
> > 
> > 
> > Hi, I don't think so! He must have upgraded up your boosts
> 
> ah you mean that he used the points up upgrade ? how much that costs ?

![image](https://github.com/user-attachments/assets/e2deb1a1-e011-4188-b552-e2be37799c94)
See in Tasks

**Comment by supmyhava** [comment]
> > > > hi mate i try use your bot
> > > > i had 67000 points in my account and when i run your bot it put me balancePoints: 17967
> > > > my points are gone ????
> > > 
> > > 
> > > Hi, I don't think so! He must have upgraded up your boosts
> > 
> > 
> > ah you mean that he used the points up upgrade ? how much that costs ?
> 
> ![image](https://private-user-images.githubusercontent.com/91886585/353077290-e2deb1a1-e011-4188-b552-e2be37799c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTg4MjcsIm5iZiI6MTcyMjI1ODUyNywicGF0aCI6Ii85MTg4NjU4NS8zNTMwNzcyOTAtZTJkZWIxYTEtZTAxMS00MTg4LWI1NTItZTJiZTM3Nzk5Yzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzMDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTJiNWQ4YzAwZDQ0ZmU1YTI3Y2M4ZjljMGYyMzk0MDgzYWE2OWRmYmY5ZmNmYmI0OTRmNjUxNDNhMjU0NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BuFQV6LWQtGLuDn2HIJptV7__wF-Flv_fr1eTY3R-E) See in Tasks

Ahhhh so that's where my points went?

**Comment by Fairmont77** [comment]
> > > > > hi mate i try use your bot
> > > > > i had 67000 points in my account and when i run your bot it put me balancePoints: 17967
> > > > > my points are gone ????
> > > > 
> > > > 
> > > > Hi, I don't think so! He must have upgraded up your boosts
> > > 
> > > 
> > > ah you mean that he used the points up upgrade ? how much that costs ?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/91886585/353077290-e2deb1a1-e011-4188-b552-e2be37799c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTg4MjcsIm5iZiI6MTcyMjI1ODUyNywicGF0aCI6Ii85MTg4NjU4NS8zNTMwNzcyOTAtZTJkZWIxYTEtZTAxMS00MTg4LWI1NTItZTJiZTM3Nzk5Yzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzMDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTJiNWQ4YzAwZDQ0ZmU1YTI3Y2M4ZjljMGYyMzk0MDgzYWE2OWRmYmY5ZmNmYmI0OTRmNjUxNDNhMjU0NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BuFQV6LWQtGLuDn2HIJptV7__wF-Flv_fr1eTY3R-E) See in Tasks
> 
> Ahhhh so that's where my points went?

yep)

**Comment by supmyhava** [comment]
> > > > > > hi mate i try use your bot
> > > > > > i had 67000 points in my account and when i run your bot it put me balancePoints: 17967
> > > > > > my points are gone ????
> > > > > 
> > > > > 
> > > > > Hi, I don't think so! He must have upgraded up your boosts
> > > > 
> > > > 
> > > > ah you mean that he used the points up upgrade ? how much that costs ?
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/91886585/353077290-e2deb1a1-e011-4188-b552-e2be37799c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTg4MjcsIm5iZiI6MTcyMjI1ODUyNywicGF0aCI6Ii85MTg4NjU4NS8zNTMwNzcyOTAtZTJkZWIxYTEtZTAxMS00MTg4LWI1NTItZTJiZTM3Nzk5Yzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzMDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTJiNWQ4YzAwZDQ0ZmU1YTI3Y2M4ZjljMGYyMzk0MDgzYWE2OWRmYmY5ZmNmYmI0OTRmNjUxNDNhMjU0NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BuFQV6LWQtGLuDn2HIJptV7__wF-Flv_fr1eTY3R-E) See in Tasks
> > 
> > 
> > Ahhhh so that's where my points went?
> 
> yep)

omg I came out so stupid XDDDDDDDD

**Comment by supmyhava** [comment]
btw i can use your bot for 3 account ?
or 1 folder each acc ?
also if i will put 3 account in same place i will get those erors ? like
[*] Error: Request failed with status code 400 
[*] Error: Request failed with status code 402
[*] Error: Request failed with status code 403
?

**Comment by Fairmont77** [comment]
> btw i can use your bot for 3 account ? or 1 folder each acc ? also if i will put 3 account in same place i will get those erors ? like [_] Error: Request failed with status code 400 [_] Error: Request failed with status code 402 [*] Error: Request failed with status code 403 ?

Try to use new version, here you can add unlimited accounts
