### ISSUE TITLE
Support multi account ?

### ISSUE THREAD

**Issue by supmyhava** [Fairmont77/OKX_Racer_bot#4]
hi mate 
your bot is support multi account ?

**Comment by Fairmont77** [comment]
> hi mate 
> 
> your bot is support multi account ?

Hi, temporarily no(

**Comment by supmyhava** [comment]
> > hi mate
> > your bot is support multi account ?
> 
> Hi, temporarily no(

ok mate thank you

**Comment by Fairmont77** [comment]
> > > hi mate
> > > your bot is support multi account ?
> > 
> > 
> > Hi, temporarily no(
> 
> ok mate thank you

try new version
