### ISSUE TITLE
can it play the race ?

### ISSUE THREAD

**Issue by supmyhava** [Fairmont77/OKX_Racer_bot#6]
hi mate
can it play the race to collect more WP and upgrade points for mining ?

**Comment by Fairmont77** [comment]
> hi mate
> 
> can it play the race to collect more WP and upgrade points for mining ?

Hi!👋🏻 
Sure, it's fully autonomously

**Comment by supmyhava** [comment]
> > hi mate
> > can it play the race to collect more WP and upgrade points for mining ?
> 
> Hi!👋🏻 Sure, it's fully autonomously

hmm i dont think so my friend he dont play the race =\

**Comment by Fairmont77** [comment]
![image](https://github.com/user-attachments/assets/0ee8da3d-c9fa-46f2-b7b2-e7354180c126)

See, if bot make wrong prediction - you get nothing, else you win, so you got points. Isn't it?

**Comment by supmyhava** [comment]
> ![image](https://private-user-images.githubusercontent.com/91886585/354253156-0ee8da3d-c9fa-46f2-b7b2-e7354180c126.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MjIyMDksIm5iZiI6MTcyMjUyMTkwOSwicGF0aCI6Ii85MTg4NjU4NS8zNTQyNTMxNTYtMGVlOGRhM2QtYzlmYS00NmYyLWI3YjItZTczNTQxODBjMTI2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxNDE4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjY1OTE0YmJiNDMzMDVmZDc4YjRlOGU0NjEyYTFmM2Q3YTgyNGY5NzllNDBhNThmYWE0MDYwYjVjNGVmYWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r9Knjp3uaX7GmWojjQMCpetGmykCNVzJq4J590Cz1Rk)
> 
> See, if bot make wrong prediction - you get nothing, else you win, so you got points. Isn't it?

ahhh sorry my friend I got confused with another bot :D
