### ISSUE TITLE
Please add .gitignore 

### ISSUE THREAD

**Issue by lucasnguyen3979** [Fairmont77/OKX_Racer_bot#8]
![image](https://github.com/user-attachments/assets/f5849fe2-caed-480b-8769-e41c1feaf1e6)

**Comment by Fairmont77** [comment]
> ![image](https://private-user-images.githubusercontent.com/25925555/354798134-f5849fe2-caed-480b-8769-e41c1feaf1e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjcwNTUsIm5iZiI6MTcyMjY2Njc1NSwicGF0aCI6Ii8yNTkyNTU1NS8zNTQ3OTgxMzQtZjU4NDlmZTItY2FlZC00ODBiLTg3NjktZTQxYzFmZWFmMWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA2MzIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMDk0NjM3Y2Q5ZWRkM2ZiZjA3ZTIxNDk1MDM5ZTgzNDdhNDEwOGRlNjI4MjAwOTc4NmZkZmExY2E1MTEwNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2y6NB6ePAfaz-xrVlnZ3cjZQWJ5CXFT2kCrERWn6PSY)

Done, thanks
